# Generated by Django 5.2.5 on 2025-08-08 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('registered', 'Registered'), ('completed', 'Completed'), ('sent', 'Sent to Central Unit'), ('received', 'Received by Admin Office')], default='registered', max_length=50),
        ),
    ]
