# Generated by Django 5.2.5 on 2025-08-18 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0002_alter_requisition_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='expense_object',
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
