# Generated by Django 5.2.5 on 2025-08-18 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0006_swap_description_field_to_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdescription',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
