# Generated by Django 5.2.5 on 2025-08-18 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0009_itemdesc_split_by_product_and_make_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdescription',
            name='text',
            field=models.CharField(max_length=255),
        ),
    ]
