# Generated by Django 5.2.5 on 2025-08-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0010_alter_itemdescription_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='observations',
            field=models.TextField(blank=True, null=True),
        ),
    ]
