# Generated by Django 5.2.5 on 2025-08-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0011_requisition_observations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='requisition_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
