# Generated by Django 5.2.5 on 2026-02-14 19:20

import django.core.validators
import django.db.models.deletion
import requisitions.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0016_itemdescription_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisitionQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=requisitions.models.quote_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), requisitions.models.validate_file_size])),
                ('original_name', models.CharField(blank=True, default='', max_length=255)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='requisitions.requisition')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_requisition_quotes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RequisitionQuoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_items', to='requisitions.requisitionquote')),
                ('requisition_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_quote_links', to='requisitions.requisitionitem')),
            ],
        ),
        migrations.AddField(
            model_name='requisitionquote',
            name='items',
            field=models.ManyToManyField(related_name='quote_links', through='requisitions.RequisitionQuoteItem', to='requisitions.requisitionitem'),
        ),
        migrations.AddConstraint(
            model_name='requisitionquoteitem',
            constraint=models.UniqueConstraint(fields=('requisition_item',), name='uniq_quote_per_requisition_item'),
        ),
    ]
