# Generated by Django 5.2.5 on 2026-02-21 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0017_requisitionquote_requisitionquoteitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisition',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
