# Generated by Django 5.2.5 on 2026-02-22 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0018_remove_requisition_category_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitionitem',
            name='manual_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='requisitionitem',
            name='description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='requisitions.itemdescription'),
        ),
    ]
