# Generated by Django 5.2.5 on 2026-02-13 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationcode',
            name='code',
            field=models.CharField(db_index=True, max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='registrationcode',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
    ]
